#!/bin/bash
COMMAND=""
BRANCH="master"
HPC=false

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -b|--branch)
    BRANCH="$2"
    shift # past argument
    ;;
    -c|--command)
    COMMAND="$2"
    shift # past argument
    ;;
    -h|--hpc)
    HPC=true
    shift # past argument
    ;;
    --default)
    DEFAULT=YES
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

if [ $HPC ]; then
  module load git
fi

gitdir="ICPE_machine_learning_workgroup"
if [ ! -d "$gitdir" ]; then
  if [ -z $GITHUB_TOKEN ]; then
    echo 'Error: Github token not set, please export GITHUB_TOKEN'
    exit 1
  fi
  git clone https://$GITHUB_TOKEN:x-oauth-basic@github.com/compsy/$gitdir.git
fi
cd $gitdir
git checkout master
git pull
git checkout $BRANCH
cd ..

learner="$(pwd)/$gitdir/learner"
docker="$(pwd)/$gitdir/docker"

if [ $HPC ]; then
  cd $docker/cluster
  mv submit.sh ~
  cd ~
  sbatch submit.sh
else
  echo "Running in docker mode"
  echo "Mounting exports location on "
  echo $loc
  loc="$(pwd)/exports"
  mkdir -p $loc
  echo $loc
  echo "Removing $loc contents"
  rm -rf $loc/*

  docker pull frbl/icpe-machine-learning
  docker run --rm -it -v $loc:/exports -v $learner:/usr/src/app/learner --name icpe frbl/icpe-machine-learning $COMMAND
fi

