#!/bin/bash
server_name=peregrine
cd ..
git add --all
git commit -am 'Running on cluster'
git push
cd -
rev=$(git rev-parse HEAD)
scp run $server_name:~/test_python/
ssh -t $server_name "cd test_python;./run -b $rev -h"
