#!/bin/bash
cd ..
git add --all
git commit -am 'Running on server'
git push
cd -
rev=$(git rev-parse HEAD)
ssh -t pro "cd docker_test;./run -b $rev"


scp -r pro:~/docker_test/exports/* ~/Desktop/exports
open ~/Desktop/exports
