#!/bin/bash
server_name=peregrine
cd ..
git add --all
git commit -am 'Running on cluster'
git push
cd -
rev=$(git rev-parse HEAD)
scp run $server_name:~/
#scp -r ../data $server_name:~/
ssh -t $server_name "rm slurm*;./run -b $rev -h"
