#!/bin/bash
server_name=pro
cd ..
git add --all
git commit -am 'Running on server'
git push
cd -
rev=$(git rev-parse HEAD)
scp run $server_name:~/docker_test/
ssh -t $server_name "cd docker_test;./run -b $rev"


scp -r pro:~/docker_test/exports/* ~/Desktop/exports
open ~/Desktop/exports
